//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebToolHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;My Page Title&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string default_basic {
            get {
                return ResourceManager.GetString("default_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- to do --&gt;.
        /// </summary>
        internal static string defaultBlogEntry {
            get {
                return ResourceManager.GetString("defaultBlogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta name=&quot;description&quot; content=&quot;Free Web tutorials&quot;&gt;
        ///  &lt;meta name=&quot;keywords&quot; content=&quot;HTML,CSS,XML,JavaScript&quot;&gt;
        ///  &lt;meta name=&quot;author&quot; content=&quot;John Doe&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;.
        /// </summary>
        internal static string defaultMeta {
            get {
                return ResourceManager.GetString("defaultMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nav class=&quot;navbar navbar-default&quot;&gt;
        ///	&lt;div class=&quot;container-fluid&quot;&gt;
        ///		&lt;div class=&quot;navbar-header&quot;&gt;
        ///			&lt;button type=&quot;button&quot; class=&quot;navbar-toggle collapsed&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#bs-example-navbar-collapse-1&quot;&gt;
        ///				&lt;span class=&quot;sr-only&quot;&gt;Toggle navigation&lt;/span&gt;
        ///				&lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
        ///				&lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
        ///				&lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
        ///			&lt;/button&gt;
        ///			&lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot;&gt;Glaucus Indie&lt;/a&gt;
        ///		&lt;/div&gt;
        ///
        ///		&lt;div class=&quot;collapse navbar-collapse&quot; id=&quot;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultNavbar {
            get {
                return ResourceManager.GetString("defaultNavbar", resourceCulture);
            }
        }
    }
}
